<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Initial schema for the Synapse RAG core:
 *   - knowledge_document  : a source file added to the knowledge base
 *   - document_chunk      : embedded, vector-searchable slices (pgvector)
 *   - conversation / chat_message : chat history
 *
 * Hand-written (not auto-generated) because the `embedding` column uses the
 * pgvector `vector` type, which Doctrine's schema tool does not emit natively.
 */
final class Version20260628120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create knowledge base + chat schema with pgvector embeddings';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'This migration targets PostgreSQL with the pgvector extension.',
        );

        $this->addSql('CREATE EXTENSION IF NOT EXISTS vector');

        $this->addSql(<<<'SQL'
            CREATE TABLE knowledge_document (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                title VARCHAR(255) NOT NULL,
                source_type VARCHAR(100) NOT NULL,
                source_path VARCHAR(1024) NOT NULL,
                status VARCHAR(255) NOT NULL,
                chunk_count INT DEFAULT 0 NOT NULL,
                error_message TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                ingested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_document_status ON knowledge_document (status)');

        $this->addSql(<<<'SQL'
            CREATE TABLE document_chunk (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                document_id INT NOT NULL,
                content TEXT NOT NULL,
                embedding vector(1536) DEFAULT NULL,
                chunk_number INT NOT NULL,
                hash VARCHAR(64) NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_chunk_document ON document_chunk (document_id)');
        // HNSW index for fast L2 nearest-neighbour search (pgvector >= 0.5).
        $this->addSql('CREATE INDEX idx_chunk_embedding ON document_chunk USING hnsw (embedding vector_l2_ops)');
        $this->addSql(<<<'SQL'
            ALTER TABLE document_chunk
                ADD CONSTRAINT fk_chunk_document FOREIGN KEY (document_id)
                REFERENCES knowledge_document (id) ON DELETE CASCADE
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE conversation (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                title VARCHAR(255) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE chat_message (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                conversation_id INT NOT NULL,
                role VARCHAR(255) NOT NULL,
                content TEXT NOT NULL,
                sources JSON NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_message_conversation ON chat_message (conversation_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE chat_message
                ADD CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id)
                REFERENCES conversation (id) ON DELETE CASCADE
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS chat_message');
        $this->addSql('DROP TABLE IF EXISTS conversation');
        $this->addSql('DROP TABLE IF EXISTS document_chunk');
        $this->addSql('DROP TABLE IF EXISTS knowledge_document');
    }
}
